### ISSUE TITLE
Two tests fail with pypy

### ISSUE THREAD

**Issue by rene-rex** [limpyd/redis-limpyd#89]
Hi,

I ran the current master branch against pypy and two tests failed (python2.7 works fine):

```
$ pypy run_tests.py
[...]
======================================================================
FAIL: test_collection_should_work_with_only_a_pk (tests.collection.CollectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/software/redis-limpyd/tests/collection.py", line 82, in test_collection_should_work_with_only_a_pk
    self.assertEqual(hits_before + 1, hits_after)  # only a sismembers
AssertionError: 9735 != 9736

======================================================================
FAIL: test_skip_exist_test_should_not_test_pk_existence (tests.collection.InstancesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/software/redis-limpyd/tests/collection.py", line 334, in test_skip_exist_test_should_not_test_pk_existence
    list(Boat.collection().instances())
  File "/home/user/software/redis-limpyd/tests/base.py", line 97, in __exit__
    executed, self.num
AssertionError: 6 commands executed, 5 expected

----------------------------------------------------------------------
Ran 301 tests in 4.977s

FAILED (failures=2)
```

I do not know whether this this is a bug in in limpyd or pypy...

**Comment by twidi** [comment]
Could you run tests against the newly published version 1.0 to see if the problem still exists? Just to be up to date. Thanks.

**Comment by rene-rex** [comment]
Hi
It seems the errors are still there:
```
$ pypy run_tests.py
[...]
======================================================================
FAIL: test_collection_should_work_with_only_a_pk (tests.collection.CollectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rex/tmp/redis-limpyd/tests/collection.py", line 91, in test_collection_should_work_with_only_a_pk
    self.assertEqual(hits_before + 1, hits_after)  # only a sismembers
AssertionError: 1607 != 1608

======================================================================
FAIL: test_collection_should_work_with_only_a_pk_and_eq_suffix (tests.collection.CollectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rex/tmp/redis-limpyd/tests/collection.py", line 104, in test_collection_should_work_with_only_a_pk_and_eq_suffix
    self.assertEqual(hits_before + 1, hits_after)  # only a sismembers
AssertionError: 1636 != 1637

======================================================================
FAIL: test_skip_exist_test_should_not_test_pk_existence (tests.collection.InstancesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rex/tmp/redis-limpyd/tests/collection.py", line 453, in test_skip_exist_test_should_not_test_pk_existence
    list(Boat.collection().instances())
  File "/home/rex/tmp/redis-limpyd/tests/base.py", line 170, in __exit__
    executed, self.num
AssertionError: 6 commands executed, 5 expected

----------------------------------------------------------------------
Ran 370 tests in 10.209s

FAILED (failures=3)
```

**Comment by twidi** [comment]
Thanks, I confirm I can reproduce this. Will try to investigate

**Comment by twidi** [comment]
I found the reason. PYPY always calls `__len__` to know how much memory is needed for the list to create.

In the limpyd collections, when `__len__` is called before the list, we ask redis to do a `scard` on the result set. When it is called after the fetch of the data, we use the collected data.

So here, PYPY calling `__len__` adds a call to `scard`, it's why we have one more call.

Is it an accepted practice to test if we are currently using PYPY, here to change the expected number of commands?

**Comment by twidi** [comment]
By the way this also means that using PYPY every call to a collection will create one more command to redis
