### ISSUE TITLE
python3.5 test failure on IndexableListFieldTest

### ISSUE THREAD

**Issue by stuaxo** [limpyd/redis-limpyd#94]
```

======================================================================
FAIL: test_pop_commands_should_correctly_deindex_one_value (tests.fields.list.IndexableListFieldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stu/projects/external/redis-limpyd/tests/fields/list.py", line 65, in test_pop_commands_should_correctly_deindex_one_value
    bar = obj.field.lpop()
  File "/home/stu/projects/external/redis-limpyd/tests/base.py", line 103, in __exit__
    executed, self.num
AssertionError: 9 != 8 : 9 commands executed, 8 expected

----------------------------------------------------------------------
Ran 301 tests in 4.720s

FAILED (failures=1)

```

**Comment by twidi** [comment]
Hello @stuaxo

It will be a pleasure to review your pull request on the subject :p

Seriously: I really have no time to focus on this for now, so if you have some, feel free to dig on this.

**Comment by stuaxo** [comment]
NP - at the moment, I'm seeing about the typed fields thing.

**Comment by twidi** [comment]
I added support for python 3.5 and 3.6 without any change in a development branch recently without encountering this error, so I close ;)
